import { StyleSheet } from 'react-native'
import { Colors, Spacing, Radius } from '@/constants/theme'

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.light.background },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  loadingText: { fontSize: 14, color: Colors.light.textTertiary },
  messagesList: { padding: Spacing.lg, paddingBottom: Spacing.sm },
  emptyMessages: { flex: 1, justifyContent: 'center' },
  empty: { alignItems: 'center' },
  emptyText: { fontSize: 14, color: Colors.light.textTertiary, textAlign: 'center', lineHeight: 20 },
  messageBubble: {
    maxWidth: '80%',
    padding: Spacing.md,
    borderRadius: Radius.lg,
    marginBottom: Spacing.sm,
  },
  myMessage: {
    backgroundColor: Colors.light.myMessageBg,
    alignSelf: 'flex-end',
    borderBottomRightRadius: Radius.sm,
  },
  theirMessage: {
    backgroundColor: Colors.light.theirMessageBg,
    alignSelf: 'flex-start',
    borderBottomLeftRadius: Radius.sm,
  },
  messageText: { fontSize: 15, lineHeight: 20 },
  myMessageText: { color: '#fff' },
  theirMessageText: { color: Colors.light.text },
  messageTime: { fontSize: 11, marginTop: Spacing.xs },
  myTime: { color: 'rgba(255,255,255,0.6)', textAlign: 'right' },
  theirTime: { color: Colors.light.textTertiary, textAlign: 'right' },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    padding: Spacing.md,
    borderTopWidth: 1,
    borderTopColor: 'rgba(41,37,36,0.06)',
    backgroundColor: Colors.light.background,
  },
  input: {
    flex: 1,
    backgroundColor: Colors.light.controlBackground,
    borderRadius: Radius.xl,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm + 2,
    fontSize: 15,
    maxHeight: 100,
    color: Colors.light.text,
    borderWidth: 1,
    borderColor: 'rgba(41,37,36,0.06)',
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: Radius.full,
    backgroundColor: Colors.light.brand,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: Spacing.sm,
  },
  sendButtonDisabled: { opacity: 0.4 },
  sendButtonText: { color: '#fff', fontSize: 18, fontWeight: '700' },
})