import { StyleSheet } from 'react-native'
import { Colors, Spacing, Radius } from '@/constants/theme'
import { AVATAR_SIZE, AVATAR_TEXT_SIZE } from '@/constants/layout'

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.light.background },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: Colors.light.background },
  loadingText: { marginTop: Spacing.md, fontSize: 14, color: Colors.light.textTertiary },
  list: { padding: Spacing.lg },
  emptyContainer: { flex: 1, justifyContent: 'center' },
  empty: { alignItems: 'center', padding: Spacing.xl },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: Colors.light.text, marginTop: Spacing.md },
  emptySubtitle: { fontSize: 14, color: Colors.light.textTertiary, textAlign: 'center', marginTop: Spacing.sm, lineHeight: 20 },
  map: { flex: 1 },
  mapOverlay: {
    position: 'absolute',
    top: Spacing.lg,
    left: Spacing.lg,
    right: Spacing.lg,
    backgroundColor: 'rgba(250,250,249,0.95)',
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(41,37,36,0.06)',
  },
  mapOverlayTitle: { fontSize: 18, fontWeight: '700', color: Colors.light.text, letterSpacing: -0.3 },
  mapOverlaySub: { fontSize: 13, color: Colors.light.textTertiary, marginTop: Spacing.xs, lineHeight: 18 },
  callout: { padding: 4, minWidth: 120 },
  calloutTitle: { fontSize: 15, fontWeight: '600', color: Colors.light.text },
  calloutMeta: { fontSize: 12, color: Colors.light.textTertiary, marginTop: 2 },
  selectedRoomPanel: {
    position: 'absolute',
    bottom: Spacing.xl,
    left: Spacing.lg,
    right: Spacing.lg,
    backgroundColor: Colors.light.background,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(41,37,36,0.06)',
  },
  selectedRoomName: { fontSize: 18, fontWeight: '700', color: Colors.light.text, letterSpacing: -0.3 },
  selectedRoomDesc: { fontSize: 13, color: Colors.light.textTertiary, marginTop: Spacing.xs },
  selectedRoomDist: { fontSize: 14, color: Colors.light.brand, marginTop: Spacing.sm, fontWeight: '600' },
  joinButton: {
    backgroundColor: Colors.light.brand,
    paddingVertical: Spacing.md + 2,
    borderRadius: Radius.md,
    alignItems: 'center',
    marginTop: Spacing.lg,
  },
  joinButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  roomHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(41,37,36,0.06)',
    backgroundColor: Colors.light.surface,
  },
  roomHeaderLeft: { flex: 1, marginRight: Spacing.md },
  roomTitle: { fontSize: 20, fontWeight: '700', color: Colors.light.text, letterSpacing: -0.3 },
  roomDescription: { fontSize: 13, color: Colors.light.textTertiary, marginTop: Spacing.xs },
  leaveButton: {
    backgroundColor: Colors.light.background,
    paddingHorizontal: Spacing.md + 2,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: 'rgba(41,37,36,0.06)',
  },
  leaveButtonText: { fontSize: 13, fontWeight: '600', color: Colors.light.textSecondary },
  personCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing.lg,
    backgroundColor: Colors.light.surface,
    borderRadius: Radius.md,
    marginBottom: Spacing.sm,
    borderWidth: 1,
    borderColor: 'rgba(41,37,36,0.03)',
  },
  avatar: {
    width: AVATAR_SIZE,
    height: AVATAR_SIZE,
    borderRadius: Radius.full,
    backgroundColor: Colors.light.brand,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: { color: '#fff', fontSize: AVATAR_TEXT_SIZE, fontWeight: '700' },
  personInfo: { flex: 1, marginLeft: Spacing.md },
  personName: { fontSize: 16, fontWeight: '600', color: Colors.light.text },
  personMeta: { fontSize: 13, color: Colors.light.textTertiary, marginTop: 2 },
})